# .pre-commit-config.yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # this is optional, use `pre-commit auto-update` to get the latest rev!
    hooks:
    -   id: check-json
    -   id: check-toml
    -   id: check-xml
    -   id: check-yaml
    -   id: detect-private-key
    -   id: forbid-submodules
    -   id: pretty-format-json
        args: ['--autofix']
    -   id: check-added-large-files
        args: ['--maxkb=500']
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
-   repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17  # Use the ref you want to point at
    hooks:
    - id: mdformat
        # Optionally add plugins
      additional_dependencies:
      - mdformat-gfm
      - mdformat-black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
    -   id: mypy
        args: [--install-types, --ignore-missing-imports, --check-untyped-defs]
-   repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black", "-l", "79"]
-   repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
    -   id: black
        args: [--line-length=79]
-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
