# .pre-commit-config.yaml
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # this is optional, use `pre-commit auto-update` to get the latest rev!
    hooks:
    -   id: check-json
    -   id: check-toml
    -   id: check-xml
    -   id: check-yaml
    -   id: detect-private-key
    -   id: forbid-submodules
    -   id: pretty-format-json
        args: ['--autofix']
    -   id: check-added-large-files
        args: ['--maxkb=500']
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
-   repo: https://github.com/executablebooks/mdformat
    rev: 0.7.22  # Use the ref you want to point at
    hooks:
    - id: mdformat
        # Optionally add plugins
      additional_dependencies:
      - mdformat-gfm
      - mdformat-black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports, --check-untyped-defs]
        additional_dependencies:
        - 'types-PyYAML'
        - 'types-requests'
        - 'types-selenium'
        - 'types-tabulate'
        - 'types-urllib3'
-   repo: https://github.com/timothycrosley/isort
    rev: 6.0.1
    hooks:
    -   id: isort
        args: ["--profile", "black", "-l", "79"]
-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black
        args: [--line-length=79]
-   repo: https://github.com/PyCQA/flake8
    rev: 7.1.2
    hooks:
    -   id: flake8
